-- Pull total number of orders that were completed on 18th March 2023
SELECT COUNT(Order_id) AS Total_Orders
FROM SALES
WHERE Date = '2023-03-18';

-- Pull total number of orders that were completed on 18th March 2023 with the first name ‘John’ and last name Doe’
SELECT COUNT(S.Order_id) AS Total_Orders
FROM SALES S
JOIN CUSTOMERS C ON S.Customer_id = C.customer_id
WHERE S.Date = '2023-03-18' AND C.first_name = 'John' AND C.last_name = 'Doe';

-- Pull total number of customers that purchased in January 2023 and the average amount spend per customer
SELECT 
    COUNT(DISTINCT Customer_id) AS Total_Customers,
    AVG(Revenue) AS Average_Spent
FROM SALES
WHERE Date >= '2023-01-01' AND Date < '2023-02-01';

-- Pull the departments that generated less than $600 in 2022
SELECT 
    I.department
FROM 
    ITEMS I
JOIN 
    SALES S ON I.Item_id = S.Item_id
WHERE 
    YEAR(S.Date) = 2022
GROUP BY 
    I.department
HAVING 
    SUM(S.Revenue) < 600;
    
-- What is the most and least revenue we have generated by an order
SELECT 
    MAX(Revenue) AS Most_Revenue,
    MIN(Revenue) AS Least_Revenue
FROM SALES;

-- What were the orders that were purchased in our most lucrative order
SELECT 
    S.Order_id, 
    S.Item_id, 
    S.Quantity, 
    S.Revenue, 
    C.first_name, 
    C.last_name
FROM 
    SALES S
JOIN 
    CUSTOMERS C ON S.Customer_id = C.customer_id
WHERE 
    S.Revenue = (SELECT MAX(Revenue) FROM SALES);